services:

    composer:
        image: composer
        volumes:
            - .:/app


    phar:
        image: composer
        volumes:
            - .:/app
        entrypoint: /usr/local/bin/php -d phar.readonly=off phar-composer.phar
        command: build . edm-sdk.phar


    test:
        image: priorist/phpunit
        build:
            context: .
        entrypoint: vendor/bin/phpunit --colors=always --coverage-text
        command: tests
        working_dir: /app
        volumes:
            - .:/app
        environment:
            EDM_URL: ${EDM_URL}
            CLIENT_ID: ${CLIENT_ID}
            CLIENT_SECRET: ${CLIENT_SECRET}


    docs:
        image: phpdoc/phpdoc
        volumes:
            - .:/data
        command: -d ./src/Client -t ./docs --title "EDM SDK" --visibility "public"
